# f=open('sr.txt','w')
# print(f.write('well done bro!!'))
# f.close()
f=open('sr.txt','w')
print(f.write('welcome to seeyou !!!'))
f.close()
f=open('sr.txt','r')
print(f.read())
f.close()
f=open('sr.txt','a')
print(f.write('welcome to seeyou !!!'))
f.close()
f=open('sr.txt','r')
s=f.read()
s=s.replace('welcome','hii')
f.close()
f=open('sr.txt','w')
f.write(s)
f.close()